services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/alist-org/alist-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3306
      - key: DB_TYPE
        # value: sqlite3
        sync: false
      - key: DB_HOST
        # value: sql6.freesqldatabase.com
        sync: false
      - key: DB_PORT
        # value: 3306
        sync: false
      - key: DB_USER
        # value: sql6586581
        sync: false
      - key: DB_PASS
        # value: H3ITdxVWjX
        sync: false
      - key: DB_NAME
        # value: sql6586581
        sync: false
      - key: DB_TABLE_PREFIX
        # value: alist_
        sync: false
      - key: CDN
        # value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: false
